### ISSUE TITLE
[Bug]: /sdcard access Operation not permitted

### ISSUE THREAD

**Issue by JeelsBoobz** [termux-play-store/termux-apps#14]
### Problem description

Can't write to /sdcard

### Steps to reproduce the behavior.

echo "" > /sdcard/a.txt
![Screenshot_2024-06-14-18-33-16-632_com termux](https://github.com/termux-play-store/termux-apps/assets/38210868/7703bc9c-2c26-483d-a6aa-37bf6d069888)

### System information

* Termux application version: 0.126
* Android OS version: 14
* Device model: POCO X3 NFC

**Comment by fornwall** [comment]
Unfortunately write permission to all of `/sdcard` is no longer granted by Android - see https://developer.android.com/about/versions/11/privacy/storage.

If you need unrestricted write access to `/sdcard` from Termux, install the [F-Droid build](https://f-droid.org/en/packages/com.termux/), which circumvents newer security restrictions on Android by targeting older API levels - but that is not possible on Google Play.

If you only need access to app-private parts, perhaps try running `termux-setup-storage` and then putting files in `~/storage/external-0` or similar.

You're also welcome to describe your high level use case, what it is you want to achieve - perhaps we can solve it somehow with either existing or new functionality!

**Comment by fornwall** [comment]
For reference, this was resolved on June 20  by Google granting the `MANAGE_EXTERNAL_STORAGE` permission also on Google Play, so after running `termux-setup-storage`  one does have write access to `/sdcard`.
