### ISSUE TITLE
[Bug]: Certain executables not working on the Play Store version, but do work in FDroid version

### ISSUE THREAD

**Issue by marcoismobile** [termux-play-store/termux-apps#23]
### Problem description

Not sure how to describe the problem, but it seems after switching to the Play Store version of Termux, certain executables are not working anymore. I am not sure if they have the same root cause, so I am creating this issue to get some pointers on how to investigate/troubleshoot or possibly fix these problems ;)

**Chezmoi**:
https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/
When trying to apply Chezmoi it is going to run some 'generated' install shell scripts, this is working without problems on the Fdroid version of Termux, but it will gives the following error on the Play Store version:

`xxx.install.sh has bad ELF magic: 23212f64`

**Powerlevel10k**:
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#why-does-powerlevel10k-spawn-extra-processes
When installing Powerlevel10k zsh extention, it downloads a 'gitstatus' executable, which works fine on the Fdroid version of Termux, but gives the following error on the Play Store version:

`Could not find a PHDR: broken executable?`

I am not sure where to look or how to troubleshoot this? Can it possible be related to 'External, non-Termux app can not yet run Termux commands (the RUN_COMMAND permission).' or is that a compleet wrong direction?

Please let me know if you want me to troubleshoot more or need more debug logs etc..
Thanks in advance!

### Steps to reproduce the behavior.

- Clean Termux installation from Play Store
- Install Chezmoi and apply some code which includes scripts (https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/)
- Install zsh+powerlevel10k (https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#manual)

### What is the expected behavior?

Normal working functionality as in the Fdroid version of Termux

### System information

* Termux application version: 0.129
* Android OS version: 14
* Device model: Pixel 8

**Comment by sleirsgoevy** [comment]
This "ELF magic" looks like a start of a shell script shebang. Looks like shebangs might be unsupported yet?

**Comment by sleirsgoevy** [comment]
It seems that termux-exec only supports the shebang pointing directly to an ELF file. Linux actually supports nested shebangs, where an interpreter of a script is a shebanged script itself.

`gitstatus` is probably a statically-linked executable, see [here](https://github.com/termux-play-store/termux-exec/).

**Comment by fornwall** [comment]
Thanks for reporting @marcoismobile, and thanks for looking into this @sleirsgoevy !

> It seems that termux-exec only supports the shebang pointing directly to an ELF file. Linux actually supports nested shebangs, where an interpreter of a script is a shebanged script itself.

Good find, seems to be the case!

**Comment by fornwall** [comment]
> gitstatus is probably a statically-linked executable, see [here](https://github.com/termux-play-store/termux-exec/).

One way around that would be to provide a Termux `gitstatus` package, which would be dynamically linked. Don't know how straightforward it would be to make Powerlevel10k use a system-provided `gitstatus` binary, instead of downloading the statically linked one?

**Comment by marcoismobile** [comment]
Thanks both for the quick replies!
This indeed make sense (that it is related to the shebangs). Do I understand correctly that this 'shebangs' (or the termux-exec package) is not used for the Fdroid version of Termux? Or is it used in another way? Because the downloaded version of gitstatus is working 'out-of-the-box' on the Fdroid version.

**Comment by fornwall** [comment]
@marcoismobile The chezmoi problem should be fixed in version `2.51.0-2` of the `chezmoi` package - can you try updating with `pkg up` and let me know if it works ok for you?

**Comment by marcoismobile** [comment]
@fornwall Just updated the chezmoi package and indeed the scripts are now working without problems!
Thanks for the fix!

**Comment by marcoismobile** [comment]
btw about the Powerlevel10k gitstatus executable, for now I just have it disabled with the ENV variable:
`export POWERLEVEL9K_DISABLE_GITSTATUS=true`

I think because it's not actually a termux repo package, fixing that is out of scope. So from my side I am fine with closing this ticket as fixed.

And again thanks for the chezmoi fix!

**Comment by fornwall** [comment]
Great, thanks a lot for following up @marcoismobile !
