### ISSUE TITLE
[Bug]: Error: Unable to locate package mkvtoolnix

### ISSUE THREAD

**Issue by um-4ir** [termux-play-store/termux-apps#27]
### Problem description

I'm trying to install mkvtoolnix tool in terminal like it installs in GitHub and fdroid versions here it give error 
**Error: Unable to locate package mkvtoolnix**
I've installed x11-repo root-repo.

### Steps to reproduce the behavior.

pkg install mkvtoolnix 

### What is the expected behavior?

It should install that tool 

### System information

* Termux application version:
*Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.06.27
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# root-repo (sources.list.d/root.list)
deb https://root-packages.termux.net/ root main
# x11-repo (sources.list.d/x11.list)
deb https://x11-packages.termux.net/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
3.0.7
Android version:
11
Kernel build information:
Linux localhost 4.14.199+-ab696 #1 SMP PREEMPT Wed Nov 22 17:41:55 CST 2023 aarch64 Android
Device manufacturer:
TECNO MOBILE LIMITED
Device model:
TECNO KG5k
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
* Android OS version:
* Android 11
* Device model:
* TECNO KG5k

**Comment by fornwall** [comment]
Thanks for reporting! It should be fixed now - does it work to install `mkvtoolnix` after doing a `pkg update`?
