### ISSUE TITLE
[Bug]: Update stuck on play store if you have f-droid version installed

### ISSUE THREAD

**Issue by seanwlk** [termux-play-store/termux-apps#8]
### Problem description

People who installed the version from f-droid of the termux-app version are getting the play store glitched because of the different signature. If you really want to diverge from the master branch you should change the package name because at the moment you broke my play store with a stuck update, i do not intend to uninstall my current termux becuase replicating the enviroment would take me a whole day

### Steps to reproduce the behavior.

Install this https://github.com/termux/termux-app/releases/tag/v0.118.0 and then you'll see that play store will start telling you to update the app with the broken release you published

### What is the expected behavior?

You should pull the current release from play store , rename the package in something like com.termux2 and do whatever then

### System information

* Termux application version: 0.118.0
* Android OS version: 14
* Device model: CPH2415

**Comment by fornwall** [comment]
Hi and thanks for reaching out!

This will be fixed shortly (as in any day now) by a new F-Droid release which will bump the version code, so that Google Play will not try to update away from the F-Droid installation.

See https://github.com/termux-play-store for more information.
